### ISSUE TITLE
Multiple Spawn Locations [Suggestion]

### ISSUE THREAD

**Issue by austina1212** [CLADevs/Envoys#3]
Hello, usually with envoys on servers they spawn in multiple locations around spawn. Would be really cool if you could add this!

**Comment by xXNiceAssasinl0** [comment]
Sure.

**Comment by xXNiceAssasinl0** [comment]
Maybe tomrrow

**Comment by SuperKali** [comment]
added on https://github.com/CLADevs/Envoys/commit/0307639c9ac5b9b8d1de40cfc3f2d747f6b405ca
